addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.0.7")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"               % "4.0.0")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                  % "2.0.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.8")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.29")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.3.7")
