name: Federation Specification Compatibility Test

on:
  pull_request:
    branches:
      - series/2.x

jobs:
  compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'sbt'
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Run assembly
        run: sbt "apolloCompatibility/assembly"

      - name: Compatibility Test
        uses: apollographql/federation-subgraph-compatibility@v2
        with:
          compose: 'apollo-compatibility/docker-compose.yaml'
          schema: 'apollo-compatibility/products.graphql'
          path: '/graphql'
          port: 4001
          debug: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # Boolean flag to indicate whether any failing test should fail the script
          failOnWarning: false
          # Boolean flag to indicate whether any required test should fail the script
          failOnRequired: false
          # Working directory to run the test from
          workingDirectory: ''